/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BreadcrumbsComponent: typeof import('./components/BreadcrumbsComponent.vue')['default']
    HeaderComponent: typeof import('./components/HeaderComponent.vue')['default']
    NavComponent: typeof import('./components/NavComponent.vue')['default']
    OfferModalComponent: typeof import('./components/OfferModalComponent.vue')['default']
    OffersComponent: typeof import('./components/OffersComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollSpy: typeof import('./components/ScrollSpy.vue')['default']
    SelectDates: typeof import('./components/SelectDates.vue')['default']
  }
}
